### ISSUE TITLE
Fix training website header nav

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#185]
The header tab on our training website needs to be revamped with a different organizational scheme to avoid word repetition (tutorial) and to define content categories. This is a task for the December 2020 release.

**Comment by abhijna** [comment]
Comments from a third party reviewer:

It is helpful to see the draft page. I do find the organization of the page a bit confusing (for example, as a novice I would expect ‘CF Tutorials’ to have information about how to find/use the data/tools from CF programs). Do you think its possible to organize the content around some main topics/headers? Maybe something like: General Tutorials, Tutorials for Researchers, Tutorials for Common Fund Programs… Or is there too much overlapping content to be able to break it out like this? Happy to brainstorm with you a bit if that would be helpful.
I also think it would be helpful to re-name some of the section headers/titles so that a novice visitor has a better idea of what the associated content is about (for example, on the General Tutorials page, rename the header/title for ‘Conda’ something like ‘Software and Computing Management Tools’). And the header ‘Releases’ at the top of the main landing page could be changed to something like ‘Latest Updates’.
For the main landing page, a fuller description of what content is included on the site would be helpful. And is there a way for people to submit feedback/questions? It would be good to have that very visible on the site.

**Comment by s-canchi** [comment]
Based on DCC feedback reorg is now part of the upcoming cycle. Current plan is to group by topics and persona. Will evaluate and reorg as necessary for next cycle.
