### ISSUE TITLE
email all the people about CP 

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#187]
Possibly we're going to send them to the new website to register...will deal with that as a concept once we're to this step. Email should have:

- dates, times, good descriptions
- links to register? or zoom links - need to decide if we're doing registration or not
- who to contact with questions (let's say Jeremy)

**Comment by ACharbonneau** [comment]
we should coordinate this with Wendy Knosp.

**Comment by jeremywalter** [comment]
DRAFT - IN PROGRESS

Greetings from the CFDE-CC!

[CFDE Cross-Pollination Events ](https://docs.google.com/spreadsheets/d/1hQAeOLkivUZZnwZ_KxfGw3neezMaWbrPk9nnFiKfQGA/edit#gid=1089477257) begin next week. 

Week 1: **How to Engage with the CFDE**: An overview of the what the CFDE-CC has been doing, the goals of the CFDE, how to participate, and an overview of resources (e.g., websites, RFCs). 45 minute webinar + 45 minute discussion and question session.

Time: Sep 29, 2020 11:00 AM Pacific Time (US and Canada) 2:00 PM Eastern (US and Canada)

Join Zoom Meeting
https://zoom.us/j/8848247758?pwd=dGh1QnluRVh4T1ZtdTJFZzNUclpOUT09

Meeting ID: 884 824 7758
Passcode: 486352
Join by SIP
8848247758@zoomcrc.com
Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
115.114.131.7 (India Mumbai)

For a better experience, we recommend joining our [Slack channel](https://join.slack.com/share/zt-hp6jm2v8-XSq5F2tVRsgb4JcTW88Xxw) so that you can comment and ask questions during the presentation.

We look forward to seeing you!

The CFDE Coordination Team

**Comment by jeremywalter** [comment]
Waiting for mail list to be approved and added to groups.io and for CP schedule to be finalized.

**Comment by jeremywalter** [comment]
This can be included in the add to groups.io avoiding sending out two concurrent mass e-mails. Current plan is to add CP details to the direct add in to groups.io with CP details.

**Comment by jeremywalter** [comment]
All e-mails have been added to the CP Group. Calendar is in the group (where zoom links can be found). 
Question:

For upcoming/future events do we want to send out e-mails for each event? Announcements for each event? How much is not enough and how much is too much? @ACharbonneau

**Comment by ACharbonneau** [comment]
that announcement looks good to me. The only change/input i have is that you should include an attachment with the meeting zoom as well so that it's easy to put on your calendar.

**Comment by jeremywalter** [comment]
I'm attaching the .ics (just can't see on the draft) :P

**Comment by jeremywalter** [comment]
Reminder from groups.io went out today (for kickoff meeting on Septebmer 29)... it does not adjust for time zones. I followed up with a special announcement highlighting PT and ET time. Future announcements will be made manually.

**Comment by jeremywalter** [comment]
Announcements are made post-meeting or next day for the upcoming meeting... reminders sent out manually the day before. Mails go out through groups.io (but not using groups.io automation).
