### ISSUE TITLE
GTEx onboarding email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#208]
In addition to the people that always are invited:

- Kristin Ardlie
- Lan Nguyen
- Francois Aguet
- Jared Nedzel
- Katherine Huang
- Lan Nguyen
- Duyen Nguyen

I'll send you Lan's email privately. The others should be in your contact sheet

I want this one sent today

**Comment by josesanchez1815** [comment]
https://doodle.com/poll/5uivrym65db5kkhk

**Comment by josesanchez1815** [comment]
Welcome to the Common Fund Data Ecosystem!

In anticipation of your funding announcement, we're having a GTEx onboarding meeting to get your management team oriented to our project management and reporting structure. 

You can help us prepare you for the meeting by:

 filling out this doodle poll https://doodle.com/poll/5uivrym65db5kkhk so that we can coordinate a Zoom meeting.

 forwarding this message to anyone else on your team who should attend the meeting - please cc ronsanchez@ucdavis.edu

 filling out our onboarding form at least 2 business days (once before the meeting so that we can set up relevant accounts necessary for the meeting.

Attached you will find an agenda for our Onboarding Meeting.

Please let us know if you have any questions or concerns.

Best,

Jose Sanchez
Training Coordinator
Common Fund Data Ecosystem Coordinating Center

**Comment by josesanchez1815** [comment]
# GTEx Onboarding Meeting
### Thursday, Sept. 24,2020 @ 6am PST (9am EST)
Zoom

**Comment by josesanchez1815** [comment]
Update from Jose: Need to send an email to schedule Bi-weekly times for GTEX

**Comment by ACharbonneau** [comment]
sorry, i talked to owen about the repeating times yesterday and am working on getting you a better schedule. poke me monday

**Comment by josesanchez1815** [comment]
Update: Jose is gathering times for the CFDE-CC and GTEx to establish regular bi-weekly meetings via doodle poll.

**Comment by josesanchez1815** [comment]
Good Afternoon Everyone!

I hope you all are having a good week.
I set up a doodle poll to check for your availability to attend biweekly meetings to ask any questions or provide feedback in regards to the CFDE project management system. Please fill out as soon as possible, so we may schedule a zoom meeting.

Thank you,

Jose Sanchez

**Comment by josesanchez1815** [comment]
@ACharbonneau

**Comment by josesanchez1815** [comment]
Sent a doodle poll for GTEx availability for biweekly meetings.

**Comment by josesanchez1815** [comment]
# GTEx Bi Weekly Meeting
## Thursday, October 22, 2020 8am PDT (11am EDT)
