### ISSUE TITLE
SPARC onboarding email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#210]
- Peter Hunter
- Bernard de Bono
- Maryann Martone
- Jyl Boline
- Jeffrey S. Grethe

**Comment by josesanchez1815** [comment]
Welcome to the Common Fund Data Ecosystem!

In anticipation of your funding announcement, we're having a SPARC onboarding meeting to get your management team oriented to our project management and reporting structure. You can help us prepare you for the meeting by:

- [ ] filling out this doodle poll [insert doodle poll] so that we can coordinate a Zoom meeting.

- [ ] forwarding this message to anyone else on your team who should attend the meeting- please cc ronsanchez@ucdavis.edu.

- [ ] filling out our [onboarding form](https://docs.google.com/forms/d/e/1FAIpQLSeMEmXWv63Fa2FpV1ssQ-xxiux0-dhx5OBnj2SHhFVlXBbpTQ/viewform) at least 2 business days before the meeting so that we can set up relevant accounts necessary for the meeting.

We need each person from SPARC who will be interacting with the project management system to be onboarded, so they would each fill out the onboarding form. If you onboarded previously, you don’t need to do it again.

Attached you will find an agenda for our Onboarding Meeting.

Please let us know if you have any questions or concerns.

Best,


Jose Sanchez
Training Coordinator
Common Fund Data Ecosystem Coordinating Center

**Comment by ACharbonneau** [comment]
@josesanchez1815 Is this in the right place? it looks like you emailed LINCS...

**Comment by josesanchez1815** [comment]
Haha Yeah I know it looks that way. I meant to edit the Common Fund Names

**Comment by ACharbonneau** [comment]
@josesanchez1815 Can you resend this email with updated time options, and be sure to include Chris, it looks like you missed him the first time

**Comment by josesanchez1815** [comment]
Update: Trying to schedule an onboarding meeting: Waiting on two more members on the email list to list doodle times.
Planning to email again to fill out. Plus not everyone is onboarded

People on our list for SPARC who need to onboard:

Peter Hunter
Bernard de Bono
Maryann Martone

People on Our list for SPARC who have yet to fill out the doodle poll.

Jyl Boline
Peter Hunter
Maryann Martone

**Comment by josesanchez1815** [comment]
# Sparc Onboarding Meeting
### Thursday, October 1, 2020 @ 8am PST (11AM EST)

**Comment by josesanchez1815** [comment]
need to follow up with biweekly meeting schedules
prioritizing other onboards

**Comment by josesanchez1815** [comment]
Email Template for Bi-Weekly Meetings
Good Afternoon Everyone,

I hope you are all doing well!


I am sending out a doodle poll to ask for your schedule availability. Could you please fill this out so we may schedule regular bi-weekly meetings?



Thank you,

Jose Sanchez

**Comment by josesanchez1815** [comment]
Email Template: Sending Schedule
Good Afternoon Everyone!
Your next scheduled bi-weekly meeting will be on [Date] at [Time] PST (Time) EST.

The agenda for the meetings is here: [Insert DCC Running Agenda](insert hyperlink)

Cheers,

Jose Sanchez

Training Coordinator - CFDE-CC

**Comment by josesanchez1815** [comment]
# CFDE - SPARC Bi-Weekly Meeting
## Thursday, November 5, 2020 @ 10-10:30AM PST (1-1:30pm EST)

**Comment by josesanchez1815** [comment]
Set up Onboarding and Bi-Weekly Meetings: Done!
