### ISSUE TITLE
LINCS onboarding email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#211]
- Avi Ma’ayan
- Sherry Jenkins
- (Zhuorui) Sherry Xie
- Minji Jeon
- John Erol Evangelista
- Maxim Kuleshov
- Kathleen Jagodnik
- Daniel Clarke

**Comment by josesanchez1815** [comment]
Welcome to the Common Fund Data Ecosystem!

In anticipation of your funding announcement, we're having a LINCS onboarding meeting to get your management team oriented to our project management and reporting structure. You can help us prepare you for the meeting by:

 

- [ ] filling out this doodle poll https://doodle.com/poll/v9at4ys8knua5z5v so that we can coordinate a Zoom meeting.

 

- [ ] forwarding this message to anyone else on your team who should attend the meeting- please cc [joses email]

 

- [ ] filling out our [onboarding form](https://docs.google.com/forms/d/e/1FAIpQLSeMEmXWv63Fa2FpV1ssQ-xxiux0-dhx5OBnj2SHhFVlXBbpTQ/viewform) at least 2 business days before the meeting so that we can set up relevant accounts necessary for the meeting.

We need each person from LINCS who will be interacting with the project management system to be onboarded, so they would each fill out the onboarding form. If you onboarded previously, you don’t need to do it again.

Attached you will find an agenda for our Onboarding Meeting.

Please let us know if you have any questions or concerns.

Best,

Jose Sanchez
Training Coordinator
Common Fund Data Ecosystem Coordinating Center

**Comment by josesanchez1815** [comment]
# LINCS Onboarding Meeting
### Tuesday, September 22, 2020 @ 10AM PST (1PM)

**Comment by josesanchez1815** [comment]
Good Afternoon Everyone,
I hope you are all doing well!
I am sending out a doodle poll to ask for your schedule availability. Could you please fill this out so we may schedule these regular bi-weekly meetings?
https://doodle.com/poll/pqxugmnzawfff3ee

If none of these dates work for you , could you please let us know which dates and times are most convenient for you?
Thank you,
Jose Sanchez

@ACharbonneau

**Comment by josesanchez1815** [comment]
I just wanted to share before I send out an email. I'm still worried that there are only two 1 hour time slots available after reviewing your schedule and Owen's.

**Comment by ACharbonneau** [comment]
please wait on this and lets chat in the morning

**Comment by josesanchez1815** [comment]
Update from Jose: Send out emails to set up bi-weekly meetings for LINCS. Similar situation as GTEx

**Comment by josesanchez1815** [comment]
Update: Jose is gathering times for the CFDE-CC and GTEx to establish regular bi-weekly meetings via doodle poll.

**Comment by josesanchez1815** [comment]
Good Afternoon Everyone!

I hope you all are having a good week.
I set up a [doodle poll](https://doodle.com/poll/sm2bkd6iaysi2knq)  to check for your availability to attend biweekly meetings to ask any questions or provide feedback in regards to the CFDE project management system. Please fill out as soon as possible, so we may schedule a zoom meeting.

Thank you,

Jose Sanchez

**Comment by josesanchez1815** [comment]
@ACharbonneau

**Comment by josesanchez1815** [comment]
# Biweekly Meeting 
### Wednesday October 7, 2020 @ 9:30am PST (12:30pm EST)

**Comment by josesanchez1815** [comment]
Email draft for review.

Good Afternoon Everyone!

I have us scheduled for our first bi-weekly meeting on Wednesday, October 7, at 9:30am-10am PST.
Here is the zoom link [insert zoom link] and I have included an attachment for our agenda https://docs.google.com/document/d/1lR1BgNhMYU_099ZUpvBqtkIKGoX0gD0pFn8ZWEK9dQ0/edit.
Thank you,

Jose Sanchez
@ACharbonneau @jeremywalter (still need to put information in the running agenda.) I have not sent an email. But this one of the times I was given on the doodle poll.  https://doodle.com/poll/sm2bkd6iaysi2knq

**Comment by ACharbonneau** [comment]
Not sure what I'm supposed to do here. Please just schedule things and send the emails, if we don't get these on peoples calendars, the times are going to get filled.

**Comment by ACharbonneau** [comment]
Pretty sure @jeremywalter sent this...please update issue

**Comment by jeremywalter** [comment]
This went out Friday, Oct 2 with a follow up message from @ACharbonneau detailing time zones and adding a calendar invite.

Good Afternoon Everyone!
Your first scheduled bi-weekly meeting will be on Wednesday, October 7, at 9:30am-10am PST.


The agenda for the meetings is here: LINCS Running Agenda 

Cheers,

Jeremy Walter

Training Coordinator - CFDE-CC

**Comment by josesanchez1815** [comment]
Email Template
Good Afternoon Everyone!
Your next scheduled bi-weekly meeting will be on [Date] at [Time] PST (Time) EST.

The agenda for the meetings is here: [Insert DCC Running Agenda](insert hyperlink)

Cheers,

Jose Sanchez

Training Coordinator - CFDE-CC

**Comment by josesanchez1815** [comment]
Done!
