### ISSUE TITLE
Kids First Onboarding email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#212]
- Adam Resnick
- Allison Heath
- Vincent Ferretti
- Jack DiGiovanna
- Tatiana Patton
- Jena Lilly
- Ryan Velasco

**Comment by josesanchez1815** [comment]
Welcome to the Common Fund Data Ecosystem!

In anticipation of your funding announcement, we're having a Kids First onboarding meeting to get your management team oriented to our project management and reporting structure. You can help us prepare you for the meeting by:

- [ ] filling out this doodle poll [insert doodle poll] so that we can coordinate a Zoom meeting.

- [ ] forwarding this message to anyone else on your team who should attend the meeting- please cc ronsanchez@ucdavis.edu

- [ ] filling out our [onboarding form](https://docs.google.com/forms/d/e/1FAIpQLSeMEmXWv63Fa2FpV1ssQ-xxiux0-dhx5OBnj2SHhFVlXBbpTQ/viewform) at least 2 business days before the meeting so that we can set up relevant accounts necessary for the meeting.

We need each person from Kids First who will be interacting with the project management system to be onboarded, so they would each fill out the onboarding form. If you onboarded previously, you don’t need to do it again.

Attached you will find an agenda for our Onboarding Meeting.

Please let us know if you have any questions or concerns.

Best,


Jose Sanchez
Training Coordinator
Common Fund Data Ecosystem Coordinating Center

**Comment by josesanchez1815** [comment]
Update: Sent Kids First an email to set up an onboarding meeting.

**Comment by josesanchez1815** [comment]
# Kids First Onboarding
### Thursday, October 15, 2020 6am PST 9am EST

**Comment by josesanchez1815** [comment]
Email will be sent out to Kids First 10/8/2020.

**Comment by josesanchez1815** [comment]
# CFDE - Kids First Bi-Weekly Meeting
## Friday, October 30th, 2020 @ 9:30am PST (12:30pm EST)

**Comment by josesanchez1815** [comment]
Onboarding and Bi-Weekly Meetings set! Done!
