### ISSUE TITLE
IDG onboarding email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#213]
- Tudor Oprea
- Avi Ma’ayan
- Jeremy Yang
- Allison Bailey
- Mike Garcia
- Tudor Oprea
- Jessica Binder
- Christina Klauber
- Cristian Bologna
- Stephen Mathias
- John Erol Evangelista
- Eryk Kropiwnicki

**Comment by josesanchez1815** [comment]
Welcome to the Common Fund Data Ecosystem!

In anticipation of your funding announcement, we're having a IDG onboarding meeting to get your management team oriented to our project management and reporting structure. You can help us prepare you for the meeting by:

- [ ] filling out this doodle poll [insert doodle poll] so that we can coordinate a Zoom meeting.

- [ ] forwarding this message to anyone else on your team who should attend the meeting- please cc ronsanchez@ucdavis.edu

- [ ] filling out our [onboarding form](https://docs.google.com/forms/d/e/1FAIpQLSeMEmXWv63Fa2FpV1ssQ-xxiux0-dhx5OBnj2SHhFVlXBbpTQ/viewform) at least 2 business days before the meeting so that we can set up relevant accounts necessary for the meeting.

We need each person from IDG who will be interacting with the project management system to be onboarded, so they would each fill out the onboarding form. If you onboarded previously, you don’t need to do it again.

Attached you will find an agenda for our Onboarding Meeting.

Please let us know if you have any questions or concerns.

Best,


Jose Sanchez
Training Coordinator
Common Fund Data Ecosystem Coordinating Center

**Comment by josesanchez1815** [comment]
Sent an email asking for their availability

10.01.20 Email Sent for set onboarding meeting.

**Comment by josesanchez1815** [comment]
# IDG Onboarding Meeting
### Thursday, October 15, 2020 @ 8AM-9AM

**Comment by josesanchez1815** [comment]
Email Template for Bi-Weekly Meetings
Good Afternoon Everyone,

I hope you are all doing well!

I am sending out a doodle poll to ask for your schedule availability. Could you please fill this out so we may schedule regular bi-weekly meetings?

Thank you,

Jose Sanchez

**Comment by josesanchez1815** [comment]
# CFDE - IDG Bi-Weekly Meetings
## Thursday, October 29th, 2020 @ 9-9:30am PST (12-12:30pm EST)

**Comment by josesanchez1815** [comment]
Done!
