### ISSUE TITLE
Metabolomics onboarding email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#214]
- Shankar Subramaniam
- Mano Maurya
- Sonal Choudhary
- Shakti Gupta
- Eoin Fahy

**Comment by josesanchez1815** [comment]
Welcome to the Common Fund Data Ecosystem!

In anticipation of your funding announcement, we're having a Metabolomics onboarding meeting to get your management team oriented to our project management and reporting structure. You can help us prepare you for the meeting by:

- [ ] filling out this doodle poll [insert doodle poll] so that we can coordinate a Zoom meeting.

- [ ] forwarding this message to anyone else on your team who should attend the meeting- please cc ronsanchez@ucdavis.edu.

- [ ] filling out our [onboarding form](https://docs.google.com/forms/d/e/1FAIpQLSeMEmXWv63Fa2FpV1ssQ-xxiux0-dhx5OBnj2SHhFVlXBbpTQ/viewform) at least 2 business days before the meeting so that we can set up relevant accounts necessary for the meeting.

We need each person from Metabolomics who will be interacting with the project management system to be onboarded, so they would each fill out the onboarding form. If you onboarded previously, you don’t need to do it again.

Attached you will find an agenda for our Onboarding Meeting.

Please let us know if you have any questions or concerns.

Best,


Jose Sanchez
Training Coordinator
Common Fund Data Ecosystem Coordinating Center

**Comment by josesanchez1815** [comment]
Sent an email with a doodle poll asking for their availability.

**Comment by josesanchez1815** [comment]
# Metabolomics Onboarding 
### Monday, October 12, 2020 @ 10am PST 1pm EST

**Comment by josesanchez1815** [comment]
Email Template for Bi-Weekly Meetings
Good Afternoon Everyone,

I hope you are all doing well!

I am sending out a doodle poll to ask for your schedule availability. Could you please fill this out so we may schedule regular bi-weekly meetings?

Thank you,

Jose Sanchez

**Comment by josesanchez1815** [comment]
# Metabolomics 1st Bi Weekly Meeting 
## Monday, November 2, 2020 @ 8am PST (11am EST)

**Comment by josesanchez1815** [comment]
CFDE - Metabolomics Bi-Weekly Meeting
Good Afternoon Everyone!
Your next scheduled bi-weekly meeting will be on Monday, November 2, 2020 @ 8am PST (11am EST)
 at 8am PST (11am EST).

The agenda for the meetings is here: [Metabolomics Running Agenda](https://docs.google.com/document/d/1cl6DuJkAK7y_Fbo8bRCVQYbXkIjrm7J0xNvJXcMEGc0/edit)

Here is the Zoom Meeting Link: [Metabolomics BiWeekly](https://zoom.us/j/95178577428?pwd=ZWlZRGVndW1CQnZiQUxYSmE4Qk5Bdz09)

Cheers,

Jose Sanchez

Training Coordinator - CFDE-CC

**Comment by josesanchez1815** [comment]
Done!
