### ISSUE TITLE
Keeping track of plug-in updates

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/training-and-engagement#237]
One issue we faced is the mkdocs-material needed to be updated and it caused issues when trying to render on readthedocs.

We need to find a way to automate plug-in updates as changes come up.
This is a space to generate ideas about how to keep track of any plug ins that need version updates.

**Comment by ACharbonneau** [comment]
A small point of clarification: The plugins *do* automatically update unless you specifically 'freeze' them tell them not to update. We have not frozen versions of any plugins on any of our sites. They all automatically update. The issue is that when the people who write the plugins update their plugins, they do not always write them with backwards compatible syntax. So, we need to make sure that we are in some way tracking *when* plugins update, and reading the release notes to make sure the update doesn't impact our site. OR we need to freeze our plugins so they don't update (and deal with any security and RTD problems that causes)

**Comment by marisalim** [comment]
for reference, this is the mkdocs changelog/upgrade/deprecations page: https://squidfunk.github.io/mkdocs-material/changelog/

**Comment by marisalim** [comment]
In the Oct release, I added a section to the [style guide](https://cfde-training-and-engagement.readthedocs-hosted.com/en/latest/CFDE-Internal-Training/Website-Style-Guide/1WebsiteNavStyle/#website-features) on checking the changelog and how to update plugins.
