### ISSUE TITLE
Make a Github auth token tutorial

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/training-and-engagement#294]
add as an internal CFDE tutorial --

```
Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
```

- https://git-scm.com/docs/git-credential-store
- https://docs.github.com/en/free-pro-team@latest/github/using-git/updating-credentials-from-the-macos-keychain
- https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
- https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication --> not listed, but Duo app works too
- https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

**Comment by s-canchi** [comment]
Steps from @ACharbonneau 
So, re github. you can either use ssh, or set up two factor auth. I went with two factor, because the button was there.

- https://github.com/settings/security
- click button
- setup with phone or whatever
- then make a PAT: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token scoped to all ‘repo’ nothing else
- then updated keychain to using PAT key https://docs.github.com/en/free-pro-team@latest/github/using-git/updating-credentials-from-the-macos-keychain
- for whatever reason, that deleted my old password but didn’t actually add it to my git, so when i pushed it asked me for my name and password. I gave it name and PAT key. That made it remember it. all is working again now.

sidenote: i store my PAT keys in my password manager because github (or whoever you make it with) will only ever show it to you once, so for instances where you need to put it multiple places, it’s not great to rely on your copy/paste remembering it
