### ISSUE TITLE
Update training site style guide

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/training-and-engagement#330]
- [x] add text highlight syntax

Text highlighting is specified in the "extra.css" file with this block:

```
.highlight_txt {
  color: #9f0bde;
  background-color: #ededed;
  padding: .25em;
}
```

The color is set to purple website-wide. Use this syntax in markdown files, where the highlighted text here is "File Repository": 
```
<span class="highlight_txt">File Repository</span> 
```

**Comment by s-canchi** [comment]
Would it be worthwhile to add a new section that lists our flyers and other documents we generate for our workshops ? The color and font info are below. Flyers have been created in Canva.

The Hex color codes for the CFDE palette from the training website:

- Main Headers: #336699
- Table headings/ landing page : #C3E1E6
- Footer: #204060

Fonts Used So Far & Sizes

- Workshop Header: Lora 37.5 Font
- Title: Lora 60 Font
- Date & Time: Montserrat 42.7 Font
- Brought to you By: Lora 35.4 Font
- Contact Training E-mail: Lora 30.5 Font

---> since we don't use these for the training website itself, i think these details can go to our Training Org google drive, where we keep workshop surveys/notes/schedule

**Comment by marisalim** [comment]
- [x] add emoji syntax

e.g., `:fontawesome-regular-trash-alt:`

specified in mkdocs.yml by:
```
- pymdownx.emoji:
     emoji_index: !!python/name:materialx.emoji.twemoji
     emoji_generator: !!python/name:materialx.emoji.to_svg
```

**Comment by s-canchi** [comment]
- [x] add header syntax style

Use the `===` under the titles for landing page. To ensure the contents occupy the full width of the page use 

```
hide:
   - toc
```
in the yaml format on top of the page.
