### ISSUE TITLE
Add some IDG training resources to the training website

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#484]
IDG sent me some info about workshops they’ve done that they have recordings for. It’s in the announcements, but they would also like them added to the training website. So adding an IDG tab to this page: https://training.nih-cfde.org/en/latest/Common-Fund-Tools/

I think this would just be links to those trainings rather than formatting them to look like our trainings. Could one of you work with Jessica to get them added? Details below

> I was writing to see if I had fwd’ you the list of previous YouTube videos made by Avi’s group representing IDG tools (see below) , but let you know about we’ve also posted a bunch from our IDG digital tools fest Nov 30th. https://youtube.com/playlist?list=PL-8k9c6dRYowAMrI0L812G6TNmZTcBDWv . If you wanted to have a linking page to IDG tutorials: https://training.nih-cfde.org/en/latest/Common-Fund-Tools/

>https://youtu.be/a0tbojE9DEU In this e-IDG presentation, Anna Calinawan, a Software Engineer from the Wang Lab, describes a collaborative project between the Ma'ayan Lab and Pei Wang Lab at ISMMS where we apply kinase enrichment analysis to analyze phosphoproteomics data from the NCI CPTAC program. The web portal that Anna developed can be accessed at: https://pancan-kea3.cptac-data-view.org.

>https://youtu.be/6gDzA2dfOrI In this e-IDG lecture Dr. Alexander Lachmann, an Assistant Professor from the Ma'ayan Lab at ISMMS, describes three projects: PrismExp, blitzGSEA, and bridgeGSEA. These are three related methods to predict gene function and incorporate such predictions within gene set enrichment analyses. Read more about PrismExp here: https://www.biorxiv.org/content/10.11.... The PrismExp Appyter can be accessed from here: https://appyters.maayanlab.cloud/#/Pr...

>https://youtu.be/m2bVYhF7MHo In this e-IDG lecture, Eryk Kropiwnicki, a Data Scientist from the Ma'ayan Lab, presents DrugShot, a web-based application and an Appyter that converts PubMed searches into ranked lists of drugs and other small molecules based on literature co-mentions. DrugShot also makes predictions about additional relevant drugs based on drug-drug LINCS L1000 gene expression similarity. The DrugShot website can be accessed at: https://maayanlab.cloud/drugshot/. The DrugShot Appyter can be accessed at: https://appyters.maayanlab.cloud/#/Dr....

**Comment by s-canchi** [comment]
I can get this added in. We are due for a release so would be good to add this as "new" content. Should we term is as content from partner institute or collaborator to indicate this was generated by outside of CFDE training team ?

@JessBinder - It would be good to put together a landing page that describes the overall project and the different tools and we can put together the table with the above links and timestamps along with one line description. Here is our [website style guide](https://github.com/nih-cfde/training-and-engagement/tree/stable/docs/Website-Style-Guide) for more information but happy to help format if you could provide some text.

**Comment by JessicaMaine** [comment]
@AviMaayan do you want to structure this a little different, via as an IDG whole "tools" table?

**Comment by ACharbonneau** [comment]
@raynamharris @jessicalumian Can you post an update here on where we got on this? Do we have a page drafted? Do we need anything else to get this published?

**Comment by JessBinder** [comment]
[Common Fund Data Ecosystem Training.docx](https://github.com/nih-cfde/training-and-engagement/files/7928695/Common.Fund.Data.Ecosystem.Training.docx)
Almost done with this file/ with tutorial structure/info

**Comment by JessicaMaine** [comment]
ok Here are our final entry requests :
[Common Fund Data Ecosystem Training-IDG_tools.docx](https://github.com/nih-cfde/training-and-engagement/files/7929507/Common.Fund.Data.Ecosystem.Training-IDG_tools.docx)
)

**Comment by raynamharris** [comment]
Okay, a draft of this page is available at  https://cfde-training-and-engagement--505.com.readthedocs.build/en/505/Common-Fund-Tools/IDG/

I used an online tool to convert the word document to a markdown document, so I think we might need to do a little formatting before it's ready to release to the public.  

One thing that would be nice would be to have a screenshot that I could attached to each YouTube hyperlink. Or... maybe I should embed the YouTube videos...

**Comment by JessicaMaine** [comment]
I tried logging in to the readthedocs, "Unauthorized Request
You currently do not have permission to view this documentation."

If you'd like I can change the word doc to an HTML with the screenshots of the youtube vids. Thank you!

**Comment by JessicaMaine** [comment]
<html>
<body>
          <div class="md-content">
            <article class="md-content__inner md-typeset">
              
                
                
<h1 id="idg-overview">Illuminating the Druggable Genome (IDG)<a class="headerlink" href="https://druggablegenome.net/" title="Permanent link">&para;</a></h1>
<p><img alt="IDG Welcome Page" src="../../images-idg/IDG.png" title="IDG Welcome Page" /></p>
				
<h3 id="idg-overview">IDG Overview<a class="headerlink" href="#idg-overview" title="Permanent link">&para;</a></h3>
				
<p>The NIH funded the Illuminating the Druggable Genome (IDG) program to improve our understanding of the properties and functions of proteins that are currently under-annotated within the three most commonly drug-targeted protein families: G-protein coupled receptors, ion channels, and protein kinases. Since 2014, the IDG Knowledge Management Center (IDG-KMC) has generated several open-access datasets and resources that jointly serve as a highly translational machine-learning-ready knowledgebases focused on human protein-coding genes and their products. The goal of the IDG-KMC is to develop comprehensive integrated knowledge for the druggable genome to illuminate the uncharacterized or poorly annotated portion of the druggable genome. The tools derived from the IDG-KMC provide either user-friendly visualizations or ways to impute knowledge about potential targets using machine learning strategies.</p>

<p>For step-by-step descriptions on how to use each web-based tool to accelerate illumination in under-studied proteins check out our Current Protocols <a href=" https://doi.org/10.1002/cpz1.355">doi: 10.1002/cpz1.355.</a></p>
				
<p>Visit <a href="https://druggablegenome.net/">https://druggablegenome.net/</a> for more information on IDG Consortium.</p>
<br>
				
<h3 id="pharos-link">Interacting with the Pharos user interface<a class="headerlink" href="#pharos-link" title="Permanent link">&para;</a></h3>
<p>Presenter: Tim Sheils, NCATS (IDG KMC)<br>
Demo outcome: Participants will learn how to browse through Pharos, upload and save lists, analyze lists, and get predicted ligand interactions. IDG Grant: KMC-UNM U24CA224370 <br>
Publication: <a href="https://doi.org/10.1093/nar/gkaa993">https://doi.org/10.1093/nar/gkaa993</a>
Link to Digital tool: <a href="https://pharos.nih.gov/"> https://pharos.nih.gov/ </a>
</p>
<p><a href="https://youtu.be/1FKp0gskGhU"><img alt="Pharos YouTube Tutorial" src="../../images-idg/IDGPharosYT_1.png" title="Pharos YouTube Tutorial" /></a></p>

				<br>
				
<h3 id="pharos-api-link">How to use Pharos API<a class="headerlink" href="#pharos-api-linkm" title="Permanent link">&para;</a></h3>
<p>(Research Database) with GraphQL API methodology allowing for more fine-tuned queries.<br> Presenters: Keith Kelleher, NCATS (IDG KMC) Demo Outcome: Participants will learn how to query the Pharos API using GraphQL. IDG Grant: KMC-UNM U24CA224370 <br>Link to Digital tool: <a href="https://pharos.nih.gov/api">https://pharos.nih.gov/api</a> </p>
<p><a href="https://youtu.be/EVir_va8xaY"><img alt="Pharos API Youtube" src="../../images-idg/IDGPharosYT_2.png" title="Pharos API Youtube"/></a></p>
	<br>			

<h3 id="harmonizome-link">The Harmonizome resource<a class="headerlink" href="#harmonizome-link" title="Permanent link">&para;</a></h3>
<p> Presenter: Andrew Rouillard,ISMMS (IDG-KMC) Harmonizome is a collection of processed datasets gathered to serve and mine knowledge about genes and proteins from over 70 major online resources. We extracted, abstracted and organized data into ∼72 million functional associations between genes/proteins and their attributes. Demo Outcome: Understanding the concepts behind constructing the Harmonizome. IDG Grant: KMC-ISMMS U24CA224260 https://maayanlab.cloud/Harmonizome, publication: https://doi.org/10.1093/database/baw100</p>
			<p><a href="https://www.youtube.com/watch?v=yGkIQjeWh9U"><img alt="Harmonizome YouTube Tutorial" src="../../images-idg/harmonizome-YT-1.png" title="Harmonizome YouTube Tutorial" /></a></p>	
				<br>
<h3 id="archs4-link">The ARCHS4 resource<a class="headerlink" href="#archs4-link" title="Permanent link">&para;</a></h3>

<p>  ARCHS4 provides access to gene counts for over 1 million samples uniformly processed from RNA-seq studies for human and mouse experiments from GEO and SRA. <br>Presenter: Alexander Lachmann, ISMMS (IDG KMC) Demo Outcome: Using the ARCHS4 user interface; Accessing ARCHS4 programmatically; Making gene function predictions with data from ARCHS4. IDG Grant: KMC-ISMMS U24CA224260 <br>Link to Digital tool: <a href="https://maayanlab.cloud/archs4/">https://maayanlab.cloud/archs4/  </a></p>
<p><a href="https://youtu.be/IxZHyf2bPjQ"> <img alt="ARCHS4 YouTube Tutorial" src="../../images-idg/ARCHS4-YT-1.png" title="ARCHS4 YouTube Tutorial"/> </a></p>

	<br>
<h3 id="prismexp-link">Making predictions about gene function with PrismExp<a class="headerlink" href="#prismexp-link" title="Permanent link">&para;</a></h3>

<p>In this e-IDG lecture Dr. Alexander Lachmann, an Assistant Professor from the Ma'ayan Lab at ISMMS, describes three projects: PrismExp, blitzGSEA, and bridgeGSEA. These are three related methods to predict gene function and incorporate such predictions within gene set enrichment analyses. <br>Read more about PrismExp here: <a href="https://www.biorxiv.org/content/10.11">https://www.biorxiv.org/content/10.11.</a> <br>The PrismExp Appyter can be accessed from here: <a href "https://appyters.maayanlab.cloud/#/PrismEXP"> PrismEXP Appyter </a></p>
<p><a href="https://youtu.be/6gDzA2dfOrI"><img alt"PrismExp YouTube Tutorial" src="../../images-idg/PrismExp-YT-1.png" title="PrismExp YouTube Tutorial"/> </a></p>
	
				
<br>				
	<h3 id="geneshot-link">Using Geneshot to illuminate knowledge about understudied targets<a class="headerlink" href="#geneshot-link" title="Permanent link">&para;</a></h3>

<p>Geneshot – Search engine developed to illuminate and promote attention to the under-studied genome producing ranked gene lists contain genes that were previously published in association with the search terms, as well as genes predicted to be associated with the terms based on data integration from multiple sources.<br> Presenter: Alexander Lachmann, ISMMS (IDG KMC) Demo outcome: Using the Geneshot user interface; Accessing Geneshot programmatically; Making gene function predictions with data from Geneshot. IDG Grant: KMC-ISMMS U24CA224260 <br>Link to Digital tool:
	<a href="https://maayanlab.cloud/geneshot/"> https://maayanlab.cloud/geneshot/</a><br> Link to Publication: Geneshot: search engine for ranking genes from arbitrary text queries, 
<a href="https://doi.org/10.1093/nar/gkz393">https://doi.org/10.1093/nar/gkz393</a> 	
			
<p><a href="https://youtu.be/VyNL7WzwQtk"><img alt"Geneshot YouTube Tutorial" src="../../images-idg/geneshot-YT-1.png" title="GeneShot YouTube Tutorial"/> </a></p>
<br>				
								
	<h3 id="tinx-link">Exploring under-studied targets with TIN-X<a class="headerlink" href="#tinx-link" title="Permanent link">&para;</a></h3>

<p>TIN-X – Target Importance and Novelty eXplorer, an interactive visualization tool for illuminating associations between diseases and potential drug targets <br>Presenter: Vincent T. Metzger, UNM (IDG KMC) Demo Outcome: Using TIN-X to visually explore understudied drug targets; Demonstration of interactive features of the TIN-X User Interface. IDG Grant: KMC-UNM U24CA224370<br> Link to Digital tool: 

<a href="https://newdrugtargets.org"> https://newdrugtargets.org</a><br> Link to Publication: TIN-X: target importance and novelty explorer. Bioinformatics. Volume 33, Issue 16, 15 August 2017, Pages 2601–2603, 
<a href="https://doi.org/10.1093/bioinformatics/btx200"> https://doi.org/10.1093/bioinformatics/btx200</a> 	
<p><a href="https://youtu.be/vBheOcupvAQ"><img alt"Tin-X YouTube Tutorial" src="../../images-idg/tinx-YT-1.png" title="Tin-X YouTube Tutorial"/> </a></p>
<br>
<h3 id="drugcentral-link">Interacting with the DrugCentral user interface<a class="headerlink" href="#drugcentral-link" title="Permanent link">&para;</a></h3>
<p>DrugCentral – Online drug compendium with annotations of mechanism of action for clinically approved drugs.<br>Presenter: Tudor Oprea, UNM (IDG KMC)<br> Demo Outcome: Participants will learn about the information content currently included in DrugCentral, from mode-of-action drug targets to side effects, chemical information, and drug formulations. The use of the L1000 gene profile similarity for drugs and the machine learning prediction of anti-SARS-CoV-2 activities will also be discussed. IDG Grant: KMC-UNM U24CA224370 <br> Link to Publication: <a href="https://doi.org/10.1093/nar/gkaa997">https://doi.org/10.1093/nar/gkaa997</a>
	<br>Link to Digital tool: <a href="https://drugcentral.org">https://drugcentral.org</a> and <a href="https://drugcentral.org/Redial">https://drugcentral.org/Redial</a>
<p><a href="https://youtu.be/2Nu689No4H0"><img alt="DrugCentral YouTube Tutorial" src="../../images-idg/drugcentralYT_1.png" title="DrugCentral YouTube Tutorial" /></a></p>
				
<br>				
				
				<h3 id="tiga-link">GWAS target illumination with TIGA<a class="headerlink" href="#tiga-link" title="Permanent link">&para;</a></h3>
<p>TIGA – Target Illumination GWAS Analytics, an algorithm, automated workflow, and web application providing rational ranking, filtering and interpretation of inferred gene–trait associations and aggregated GWAS evidence by leveraging existing curation and harmonization efforts from the NHGRI-EBI GWAS Catalog. <br>Presenter: Jeremy Yang, UNM (IDG KMC) Demo outcome: This demo will feature the TIGA web app as a tool for conveniently finding, prioritizing, and exploring gene-trait associations from aggregated GWAS evidence, in the context of drug target illumination scientific use cases. IDG Grant: KMC-UNM U24CA224370 <br> Link to Publication:  TIGA: target illumination GWAS analytics <a href="https://doi.org/10.1093/bioinformatics/btab427">https://doi.org/10.1093/bioinformatics/btab427</a>
	<br>Link to Digital tool: <a href="https://unmtid-shinyapps.net/shiny/tiga/">https://unmtid-shinyapps.net/shiny/tiga/</a>
<p><a href="https://youtu.be/vK8K39BIq80 "><img alt="TIGA YouTube Tutorial" src="../../images-idg/tigaYT_1.png" title="TIGA YouTube Tutorial" /></a></p>
				
	<br>			
				
				<h3 id="kea3-link">Prioritizing kinases for lists of proteins and phosphoproteins with KEA3<a class="headerlink" href="#kea3-link" title="Permanent link">&para;</a></h3>
<p>In this e-IDG presentation, Anna Calinawan, a Software Engineer from the Wang Lab, describes a collaborative project between the Ma'ayan Lab and Pei Wang Lab at ISMMS where we apply kinase enrichment analysis to analyze phosphoproteomics data from the NCI CPTAC program.<br> The web portal that Anna developed can be accessed at: <a href="https://pancan-kea3.cptac-data-view.org">https://pancan-kea3.cptac-data-view.org</a>
<p><a href="https://youtu.be/a0tbojE9DEU"><img alt="KEA3 YouTube Tutorial" src="../../images-idg/kea3YT_1.png" title="KEA3 YouTube Tutorial" /></a></p>
 <br>
				
				<h3 id="drugshot-link">Converting PubMed searches to drug sets with the DrugShot Appyter<a class="headerlink" href="#drugshot-link" title="Permanent link">&para;</a></h3>
<p>In this e-IDG lecture, Eryk Kropiwnicki, a Data Scientist from the Ma'ayan Lab, presents DrugShot, a web-based application and an Appyter that converts PubMed searches into ranked lists of drugs and other small molecules based on literature co-mentions. DrugShot also makes predictions about additional relevant drugs based on drug-drug LINCS L1000 gene expression similarity. <br>The DrugShot website can be accessed at: <a href="https://maayanlab.cloud/drugshot/">https://maayanlab.cloud/drugshot/</a>.<br> The DrugShot Appyter can be accessed at: <a href="https://appyters.maayanlab.cloud/#/DrugShot">DrugShot Appyter</a>

<p><a href="https://youtu.be/m2bVYhF7MHo"><img alt="DrugShot YouTube Tutorial" src="../../images-idg/drugshotYT_1.png" title="DrugShot YouTube Tutorial" /></a></p>
				
				
				</body>
</html>

**Comment by JessBinder** [comment]
[](url)

**Comment by JessicaMaine** [comment]
oops.

**Comment by JessicaMaine** [comment]
https://github.com/JessBinder/idg-cfde/blob/main/doc/images/CFDE-IDG-tools.html

and I've uploaded the png snapshots there too. 

https://github.com/JessBinder/idg-cfde/blob/main/doc/images/

**Comment by raynamharris** [comment]
Thanks @JessBinder! I downloaded your images and added them to this PR/repo. I kept the markdown formatting, but I was able to add and link the screenshots. I also went though and turned the paragraph descriptions into bullet point lists.

Ah yes, you probably haven't been added to our ReadTheDocs account. Here are a few screen shots. I'm pretty happy with this. Let me know if you see anything that needs updating. 

![Screen Shot 2022-01-31 at 12 36 13 PM](https://user-images.githubusercontent.com/7544197/151869596-e6061908-9495-4ee9-8e6f-fe7fd16f70ac.png)
![Screen Shot 2022-01-31 at 12 36 35 PM](https://user-images.githubusercontent.com/7544197/151869603-fbc248a8-6953-44c2-9723-15d2b258f24f.png)
![Screen Shot 2022-01-31 at 12 36 57 PM](https://user-images.githubusercontent.com/7544197/151869608-dcf591e5-f63e-4b2b-8b33-cccf2b8abe29.png)

**Comment by JessicaMaine** [comment]
YAS!!!! looks great! just note that we do have a live link for the manuscript now!  https://doi.org/10.1002/cpz1.355 

otherwise looks awesome!

**Comment by JessicaMaine** [comment]
Sorry for reopening, (I'm writing up the monthly progress report) but I haven't seen any uploads to the https://training.nih-cfde.org/en/latest/Common-Fund-Tools/

**Comment by raynamharris** [comment]
Hi @JessBinder, thanks for the nudge. We have not merged the latest updates from the dev branch to the stable branch. I'll aim to do this on Tuesday, Feb 15.
