### ISSUE TITLE
2020 Outreach to DCCs

### ISSUE THREAD

**Issue by RebeccaBoyles** [nih-cfde/training-and-engagement#55]
Sent the below template to DCCs.

Having completed the initial cross-pollination meeting and as you are preparing to ramp up your CFDE engagement, the CFDE engagement team would like to reconnect with your program and identify areas where we can provide custom support and assist you with your CFDE integration activities. As your point of contact with the engagement team, I would like to identify any questions or concerns you may have, find the answers/solutions, and work with you to build a productive relationship with the CFDE. 

As a first step in re-invigorating this dialogue, we would like to schedule some time for a focused discussion on some of the more immediately relevant topics across CFDE teams. At present, our engagement team is looking to build consensus and bolster knowledge around the following core components:

STRIDES: The NIH Science and Technology Research Infrastructure for Discovery, Experimentation, and Sustainability (STRIDES) Initiative negotiates with major cloud providers to obtain discounted services for NIH projects.

C2M2: C2M2 is a flexible standard for describing biomedical experimental data that will be used across CFDE members to support cross-platform searches and dataset aggregation. 

RAS: Researcher Auth Service (RAS) APIs will be offered by the NIH's Center for Information Technology by the end of 2020 to provide consistent and user-friendly user authentication across NIH data resources.

FAIRshake: FAIRshake is a system developed by the CFDE to evaluate the FAIRness (Findability, Accessibility, Interoperability, and Reusability) of digital objects belonging to DCCs.

Our engagement team would like to meet with you sometime in the next few weeks to discuss the topics above as well as any other areas of interest to you. Please be on the lookout for a poll for scheduling this meeting. Please let me know if there is anyone not already on the recipient list for this email who you would like to attend. Following that, I will work over the coming months on any concerns and questions you might have about these topics as we collectively build a more cohesive data ecosystem.

**Comment by dcfcjcheadle** [comment]
[FAIRshake presentation to DCCs located here](https://docs.google.com/presentation/d/17uE2hOsgpZ4junPZrQbwt5vt4m2e7qTgPnB_8CEQRuY/edit#slide=id.p4).  **Created 29 MAY 2020**, will be updated as necessary.

**Comment by ACharbonneau** [comment]
Hey all! A couple requests: 

1. Could you CC me when you send it things like this so I can make sure I'm not trying to coordinate things with the same people at the same times

2. It would be great if you could clarify that you guys are point of contact for them to ask questions about those four areas. Currently it reads that you're the main point of contact for all engagement with them, and that's going to cause a lot of confusion, since I'm still doing all of the day to day engagement, planning all the events and organizing all the training for them. 

Also please note that I'm actively working to set up deep dives with the DCCs we didn't visit last year. That doesn't mean you can't talk to them about the model, FAIR, etc. The deep dives and your meeting should have mostly not overlapping topics, but again, we don't want to be all demanding time of the same people at once, and both be saying we're their main contact point. Or else we all look like we don't know what's happening.

**Comment by RLC-DCPPC** [comment]
Hi @RebeccaBoyles . Thanks for reaching out. Please keep @ACharbonneau informed on all DCC contacts and let her know about the DCC contact log you are maintaining. 

@owhite, let's discuss dividing the engagement work along the lines recommended by Amanda above: She will be the point of the spear and RTI will provide support and be available to answer questions on demand from the (ideally expanding list of) DCCs we have already dove with. Make sense?

**Comment by RebeccaBoyles** [comment]
@RLC-DCPPC Thanks for the clarification!
@ACharbonneau The communications log is here: https://docs.google.com/spreadsheets/d/1M6iLKBZYxawpE4n8pITFOgiQURlY8r9X5yTFqlpdUd4/edit#gid=0 
Please add your notes. We will be updating regularly to reflect our activity.

**Comment by dcfcjcheadle** [comment]
The invitation to the technical topic presentations was sent to the **LINCS** team today.  The presentation is scheduled for **Friday, June 26 @ 1:00 PM EST**.

**Comment by dcfcjcheadle** [comment]
The invitation to the technical topic presentations was sent to the **Metabolomics** team today. The presentation is scheduled for **Wednesday, July 1 from 12:00 PM - 1:00 PM Eastern.**

**Comment by RLC-DCPPC** [comment]
Hi. Could you post a link to your presentation decks?

**Comment by ngaddis** [comment]
Here's the link: https://docs.google.com/presentation/d/1UhbfeCiWwsLidE4r7p00xe449JViPLwmQ5r37BWFMGY/edit?usp=sharing

We're still tweaking it a bit, but it's mostly final.

**Comment by RLC-DCPPC** [comment]
Great. Thanks @ngaddis. 

@rpwagner has some ideas for topics he'd like you to bring up relative to RAS.

**Comment by ngaddis** [comment]
@rpwagner Let me know if you would like to discuss. Alternatively, you can share the topics here.

**Comment by swandle06** [comment]
I've set up Google Docs to capture the running notes from our meetings with the different DCCs here:
https://drive.google.com/drive/folders/1O_v_3H8Zt7UMaLHObQLmm5Bcz1xrX4F2
The LINCS document includes notes from our introductory meeting last Friday. The other docs are just stubs at this point until we have meetings with those programs in the coming weeks.

**Comment by swandle06** [comment]
In addition to John's notes above, we have the following meetings scheduled thus far:
**4DN** is scheduled for **Monday, June 29 from 4:00 PM - 5:00 PM Eastern**.
**SPARC** is scheduled for **Tuesday, June 30 from 3:00 PM - 4:00 PM Eastern**.

**Comment by ngaddis** [comment]
@RLC-DCPPC @rpwagner We have now met with 4 of the DCCs and have one more meeting coming up. Rick - since we were never able to touch base about the security-related topics you wanted to include, we'll have to use a different avenue to get the information you need. Let me know if we can help out in any way. We could facilitate contact with the DCCs if that would be helpful.
